apps/clubs/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template


urlpatterns = patterns('',


    # all clubs
    url(r'^$', 'clubs.views.clubs', name="clubs"),
    # Add club
    url(r'^add_club/$', 'clubs.views.add_club', name="add_club"),
    # a club details
    url(r'^details/(?P<id>\d+)/$', 'clubs.views.details', name="club_details"),
    url(r'^destroy/(?P<id>\d+)/$', 'clubs.views.destroy', name='club_destroy'),
    #edit club
    url(r'^edit/(?P<id>\d+)/$', 'clubs.views.edit', name='club_edit'),
   #join club
    url(r'^join/(?P<id>\d+)/$', 'clubs.views.join', name='club_join'),
    #leave club
    url(r'^leave/(?P<id>\d+)/$', 'clubs.views.leave', name='club_leave'),
    # Map
    url(r'^map/$', 'clubs.views.map', name="map"),
    (r'^newmember/$',  direct_to_template, {'template': 'clubs/newmember.html'}),

)

urls.py
# -*- coding: utf-8 -*-
from django.conf.urls.defaults import *
from django.conf import settings
from django.views.generic.simple import direct_to_template

from django.contrib import admin
admin.autodiscover()

#from account.openid_consumer import PinaxConsumer
from blog.feeds import BlogFeedAll, BlogFeedUser
from bookmarks.feeds import BookmarkFeed
from microblogging.feeds import TweetFeedAll, TweetFeedUser, TweetFeedUserWithFriends


tweets_feed_dict = {"feed_dict": {
    'all': TweetFeedAll,
    'only': TweetFeedUser,
    'with_friends': TweetFeedUserWithFriends,
}}

blogs_feed_dict = {"feed_dict": {
    'all': BlogFeedAll,
    'only': BlogFeedUser,
}}

bookmarks_feed_dict = {"feed_dict": { '': BookmarkFeed }}


if settings.ACCOUNT_OPEN_SIGNUP:
    signup_view = "account.views.signup"
else:
    signup_view = "signup_codes.views.signup"


urlpatterns = patterns('',
    url(r'^$', 'views.homepage_view', name="home"),

    url(r'^admin/invite_user/$', 'signup_codes.views.admin_invite_user', name="admin_invite_user"),
    url(r'^account/signup/$', signup_view, name="acct_signup"),
    
    (r'^photologue/', include('photologue.urls')),
    (r'^about/', include('about.urls')),
    (r'^account/', include('account.urls')),
    #(r'^openid/(.*)', PinaxConsumer()),
    (r'^bbauth/', include('bbauth.urls')),
    (r'^authsub/', include('authsub.urls')),
    (r'^profiles/', include('profiles.urls')),
    (r'^blog/', include('blog.urls')),
    (r'^tags/', include('tag_app.urls')),
    (r'^invitations/', include('friends_app.urls')),
    (r'^notices/', include('notification.urls')),
    (r'^messages/', include('messages.urls')),
    (r'^announcements/', include('announcements.urls')),
    (r'^tweets/', include('microblogging.urls')),
    (r'^tribes/', include('tribes.urls')),
    (r'^comments/', include('threadedcomments.urls')),
    (r'^robots.txt$', include('robots.urls')),
    (r'^i18n/', include('django.conf.urls.i18n')),
    (r'^bookmarks/', include('bookmarks.urls')),
    (r'^admin/(.*)', admin.site.root),
    (r'^photos/', include('photos.urls')),
    (r'^avatar/', include('avatar.urls')),
    (r'^swaps/', include('swaps.urls')),
    (r'^events/', include('events.urls')),
    (r'^locations/', include('locations.urls')),
    (r'^clubs/', include('clubs.urls')),
    (r'^universities/', include('universities.urls')),
    (r'^projects/', include('projects.urls')),
    
    (r'^feeds/tweets/(.*)/$', 'django.contrib.syndication.views.feed', tweets_feed_dict),
    (r'^feeds/posts/(.*)/$', 'django.contrib.syndication.views.feed', blogs_feed_dict),
    (r'^feeds/bookmarks/(.*)/?$', 'django.contrib.syndication.views.feed', bookmarks_feed_dict),
)

## @@@ for now, we'll use friends_app to glue this stuff together

from photos.models import Image

friends_photos_kwargs = {
    "template_name": "photos/friends_photos.html",
    "friends_objects_function": lambda users: Image.objects.filter(is_public=True, member__in=users),
}

from blog.models import Post

friends_blogs_kwargs = {
    "template_name": "blog/friends_posts.html",
    "friends_objects_function": lambda users: Post.objects.filter(author__in=users),
}

from microblogging.models import Tweet

friends_tweets_kwargs = {
    "template_name": "microblogging/friends_tweets.html",
    "friends_objects_function": lambda users: Tweet.objects.filter(sender_id__in=[user.id for user in users], sender_type__name='user'),
}


from bookmarks.models import Bookmark

friends_bookmarks_kwargs = {
    "template_name": "bookmarks/friends_bookmarks.html",
    "friends_objects_function": lambda users: Bookmark.objects.filter(saved_instances__user__in=users),
    "extra_context": {
        "user_bookmarks": lambda request: Bookmark.objects.filter(saved_instances__user=request.user),
    },
}

urlpatterns += patterns('',
    url('^photos/friends_photos/$', 'friends_app.views.friends_objects', kwargs=friends_photos_kwargs, name="friends_photos"),
    url('^blog/friends_blogs/$', 'friends_app.views.friends_objects', kwargs=friends_blogs_kwargs, name="friends_blogs"),
    url('^tweets/friends_tweets/$', 'friends_app.views.friends_objects', kwargs=friends_tweets_kwargs, name="friends_tweets"),
    url('^bookmarks/friends_bookmarks/$', 'friends_app.views.friends_objects', kwargs=friends_bookmarks_kwargs, name="friends_bookmarks"),
)

if settings.SERVE_MEDIA:
    urlpatterns += patterns('',
        (r'^site_media/', include('staticfiles.urls')),
    )

apps/clubs/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
from universities.models import University

from django.utils.translation import ugettext_lazy as _

    
class Club(models.Model):
    """
    Club with its details
    """
    title = models.CharField(_(u'Назва'), max_length=200)
    #university = models.ForeignKey(University)
    #while use just plain text university field
    university = models.CharField(max_length=1024, blank=True, null=False, default='')
    description = models.TextField(blank=True, null=False, default='')
    date = models.DateField(_(u'Дата створення'), default=datetime.now)
    address = models.TextField(_(u'Адреса'), blank=True)
    admin = models.ForeignKey(User)
    
    members = models.ManyToManyField(User, related_name='%(class)s_members', verbose_name=u"члени", blank=True)
    location = models.CharField(_(u'Місцезнаходження'), max_length=200)
	
    def __unicode__(self):
        return self.title
        
    def user_is_member(self, user):
        return user in self.members.all()        

class Verification(models.Model):
	club = models.ForeignKey(Club)
	member = models.ForeignKey(User)
	is_approved = models.BooleanField(u'Підтвердити', default = True)

apps/clubs/forms.py
# -*- coding: utf-8 -*-
from datetime import datetime
from django import forms
from django.utils.translation import ugettext_lazy as _


from django.utils import simplejson
from django.forms.widgets import Textarea
from django.utils.safestring import mark_safe
from django.forms.util import flatatt
from django.utils.html import conditional_escape
from django.utils.encoding import force_unicode


from clubs.models import Club

class EventAddressWidget(Textarea):
    def render(self, name, value, attrs=None):
        result = super(EventAddressWidget, self).render(name, value, attrs=attrs)
        result += mark_safe(u'<input style ="float: right; margin-right: 33px; margin-top: 5px;"  type="button" value="Знайти на мапі" onclick="codeAddress()">')
        return result

class ClubForm(forms.ModelForm):
    location = forms.CharField(initial="(48.464954, 35.044956)", #dnipropetrovsk
                               widget=forms.HiddenInput)
    address = forms.CharField(label = _(u'Адреса'),widget=EventAddressWidget())
                               
    class Meta:
        model = Club
        exclude = ('members')
        
    def __init__(self, user=None, *args, **kwargs):
        self.user = user
        super(ClubForm, self).__init__(*args, **kwargs)
    

apps/clubs/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render_to_response, get_object_or_404
from django.http import HttpResponseRedirect, get_host
from django.template import RequestContext
from django.db.models import Q
from django.http import Http404
from django.core.urlresolvers import reverse
from django.core.exceptions import ObjectDoesNotExist
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

from clubs.models import Club, Verification
from universities.models import University
from clubs.forms import *

@login_required
def map(request, template_name="clubs/map.html"):
	return render_to_response(template_name)


@login_required
def destroy(request, id):
	"""
	latest ivents
	"""
	club = Club.objects.get(id = id)
	club.members.all().delete()
	club.delete()

	redirect_to = '/clubs/'

	return HttpResponseRedirect(redirect_to)



@login_required
def details(request, id, template_name="clubs/details.html"):

	club = Club.objects.get(id = id)
	
	is_me = False
	is_member = False

	if request.user == club.admin:
		is_me = True


	try:
		is_approved = Verification.objects.get(club = club, member = request.user).is_approved
		if is_approved:
			is_wait_for_approve = False
		else:
			is_wait_for_approve = True
	except:
		is_wait_for_approve = False
	members = []
	verifications = Verification.objects.filter(club = club)
	for ver in verifications:
		if ver.is_approved:
			members = members + [ver.member]

	for member in members:
		if member == request.user:
			is_member = True
			break

    
	return render_to_response(template_name, {
    "club": club,
	"is_me": is_me,
	"is_member": is_member,
	"members": members,
	"is_wait_for_approve": is_wait_for_approve,
    }, context_instance=RequestContext(request))


@login_required
def add_club(request, form_class=ClubForm, template_name="clubs/add_club.html"):
    club_form = form_class(request.user)
    if request.method == "POST":
        if request.POST["action"] == "create":
            club_form = form_class(request.user, request.POST)
            
            if club_form.is_valid():
                club = club_form.save(commit=False)
                
                club.save()
                return HttpResponseRedirect(reverse("clubs"))
    return render_to_response(template_name, {
        "club_form": club_form
    }, context_instance=RequestContext(request))
        


@login_required
def edit(request, id, form_class=ClubForm,template_name="clubs/edit.html"):


    club = get_object_or_404(Club, id=id)
    club_form = form_class(request.user, instance=club)
    
    if request.user == club.admin:
        is_admin = True
    else:
        is_admin = False
        
   
    if request.method == "POST":
        if request.POST["action"] == "update":
	        club_form = form_class(request.user, request.POST, instance=club)
        if club_form.is_valid():
                    club = club_form.save(commit=False)
                    club.save()
                    return HttpResponseRedirect(reverse("clubs"))
        
                
    return render_to_response(template_name, {
        "club_form": club_form,
        "club": club,
        "is_admin" : is_admin,
    }, context_instance=RequestContext(request))


#@login_required
def clubs(request, template_name="clubs/clubs.html"):
	
	clubs = Club.objects.order_by("title")
    
	return render_to_response(template_name, {
		"clubs": clubs,
		}, context_instance=RequestContext(request))


@login_required
def join(request, id, template_name="clubs/details.html"):

	club = Club.objects.get(id = id)
	
	members = club.members.all()
	is_member = False	

	for member in members:
		if member == request.user:
			is_member = True
			break	
		
	if is_member:
		pass
	else:
		club.members.add(request.user)
		club.verification_set.create(member = request.user)
		club.save()

	if request.user.is_staff:			#админ вступает в клуб
		verification = Verification.objects.get(club = club, member = request.user)
		verification.is_approved = True
		verification.save()

	return HttpResponseRedirect('/clubs/details/' + club.id.__str__())



	
@login_required
def leave(request, id, template_name="club/details.html"):
    club = Club.objects.get(id = id)


    if club.user_is_member(request.user):
        club.members.remove(request.user)

    verifications = Verification.objects.filter(club = club)
    for ver in verifications:
        if ver.member == request.user:
            ver.delete()

    club.save()
    include_kwargs = {"id": club.id}
    redirect_to = reverse("club_details", kwargs=include_kwargs)
    return HttpResponseRedirect(redirect_to)

templates/clubs/add_club.html
{% extends "clubs/base.html" %}

{% load i18n %}
{% load uni_form %}




{% block body_param %} onload="initialize()" {% endblock %}


{% block body %}
 <div class="right_panel">
        {% include "map.html" %}

 </div>
    		
   
<div class="left_panel">

<form class="uniForm" id="edit-profile" method="POST" action="">
        <fieldset class="inlineLabels">
          {{ club_form|as_uni_form }}
            <div class="form_block">
            <input type="hidden" name="action" value="create" />
            <input type="submit" value="{% trans "Створити" %}"/>
            </div>
        </fieldset>
    </form>


{% endblock %}

{% block extra_body %}

		<link type="text/css" href="{{ STATIC_URL }}pinax/css/jquery-ui-1.8.14.custom.css" rel="stylesheet" />	
   		<script type="text/javascript" src="{{ STATIC_URL }}pinax/js/topics.js"></script>
		<script type="text/javascript" src="{{ STATIC_URL }}pinax/js/jquery-1.5.1.min.js"></script>
		<script type="text/javascript" src="{{ STATIC_URL }}pinax/js/jquery-ui-1.8.14.custom.min.js"></script>

<script type="text/javascript">
	$(function() {

		$( "#id_date" ).datepicker({ dayNamesMin: ['Нед', 'Пон', 'Вівт', 'Сер', 'Чт', 'Пт', 'Суб'], firstDay: 1, dateFormat: 'yy-mm-dd',  monthNames: ['Січень','Лютий','Березень','Квітень','Травень','Червень','Липень','Серпень','Вересень','Жовтень','Листопад','Грудень'] });
	});
	</script>


{% endblock %}

templates/clubs/base.html
{% extends "site_base.html" %}

{% load i18n %}
{% load group_tags %}

{% block body_class %}clubs{% endblock %}

{% block subnav %}


        <ul>
    	{% if is_me and club %}
		    <li><a href="/clubs/edit/{{ club.id }}">  Редагувати клуб </a></li>
		    <li><a href="/clubs/destroy/{{ club.id }}"> Видалити клуб </a></li>
    	{% endif %}
    	
       	{% if user.is_staff and club %}
		    <li><a href="/clubs/edit/{{ club.id }}">  Редагувати клуб </a></li>
		    <li><a href="/clubs/destroy/{{ club.id }}"> Видалити клуб </a></li>
    	{% endif %}

    	
        {% if club %}    	
            {% if is_member %}
		        <a href="/clubs/leave/{{ club.id }}"> Вийти з клубу </a>
	        {% else %}
	            {% if not is_wait_for_approve %}
		            <a href="/clubs/join/{{ club.id }}">  Приєднатись до клубу </a>
	            {% endif %}
	        {% endif %}
     
            <li><a href="/clubs/add_club/">{% trans "Додати клуб" %}</a></li>
        </ul>
    {% else %}
        &nbsp;
    {% endif %}
{% endblock %}

templates/clubs/clubs.html
{% extends "clubs/base.html" %}

{% load i18n %}
{% load humanize %}
{% load pagination_tags %}
{% load tagging_tags %}
{% load group_tags %}
{% load threadedcommentstags %}
{% load theme_tags %}



{% block body %}
    
    <h1>Клуби</h1>
    
	
        {% for club in clubs %}

		<a href="{% groupurl club_details group id=club.id %}"> <P> {{ club.title }} - {{ club.address }} </P> </a>        
		{% endfor %}
        
	

    
    
{% endblock %}

templates/clubs/details.html
{% extends "clubs/base.html" %}

{% load i18n %}
{% load humanize %}
{% load pagination_tags %}
{% load tagging_tags %}
{% load group_tags %}
{% load threadedcommentstags %}
{% load theme_tags %}
{% load comments_tag %}
{% load avatar_tags %}

{% block head_title %}{% blocktrans %}Деталі клубу{% endblocktrans %}{% endblock %}




{% block body_param %} onload="initialize()" {% endblock %}
{% block body %}

    <div class="right_panel">
        {% include "map.html" %}
    <input id="id_location" type="hidden" class="textinput" name="location" maxlength="200" value = "(48.464954, 35.044956)"/>
    </div>
    
      <div class="left_panel">


    <h1>{% trans "Деталі" %}</h1>

	<div id="div_id_title" class="ctrlHolder">
	           <label for="id_title">                    
	                   Назва:
	           </label>
	        	{{ club.title }} 
    </div>

	<div id="div_id_university" class="ctrlHolder">
	           <label for="id_university">                    
	                   Університет:
                   </label>
                         
                   {{club.university}}
     
    </div>

    <div id="div_id_description">
            <label>{% trans "Опис клубу" %}</label>:
            <p>
                {{club.description}}
            </p>
    </div>

	<div id="div_id_address" class="ctrlHolder">
	           <label for="id_address">                    
	                   Адреса:
	           </label>
	      {{ club.address }} 
    </div>

	<div id="div_id_date" class="ctrlHolder">
	           <label for="id_date">                    
	                   Дата створення:
	           </label>
	        {{ club.date }} 
    </div>

	<div id="div_id_date" class="ctrlHolder">
	           <label for="id_date">    
	</div>                
	                   
<h3>Адміністратор клубу:</h3>
	           </label>
	         
<div name = "admin" style="float:left; margin: 10px; text-align: center">  
		<div name = "avatar">
				<a href="{% url profile_detail club.admin %}">
					<img src="{% avatar_url club.admin 80 %}" alt="Avatar of {{ club.admin }}"/> </a> </div>	
			<div name = "username">
				<a href="{% url profile_detail club.admin %}"> {{ club.admin.get_profile }} </a> </div>
		</div>
    </div>
<br>



        <h3 style = 'clear:left'> Члени клубу:</h3>
	{% if is_wait_for_approve %}
		Ваша заявка на членство у клубі на стадії розглядання 
	{% endif %}
	<div name = "members" class="thumb-row clearfix">
    {% for member in members %}
        <div name = "member" style="float:left; margin: 10px; text-align: center">  
			<div name = "avatar">
				<a href="{% url profile_detail member.username %}">
					<img src="{% avatar_url member 80 %}" alt="Avatar of {{ member.get_profile }}"/> </a> </div>
			<div name = "username">
				<a href="{% url profile_detail member.username %}"> {{ member.get_profile }} </a> </div>
		</div>
	{% endfor %}
	</div>


</div>
{% endblock %}

templates/clubs/edit.html
{% extends "clubs/base.html" %}

{% load i18n %}
{% load uni_form %}


{% block body_param %} onload="initialize()" {% endblock %}
{% block body %}
 {% if is_admin or request.user.is_staff %}  
 <div class="right_panel">
        {% include "map.html" %}
    </div>

    
<div class="left_panel">
  
    <form class="uniForm" id="edit-profile" method="POST" action="">
        <fieldset class="inlineLabels">
            {{ club_form|as_uni_form }}
            <div class="form_block">
            <input type="hidden" name="action" value="update" />
            <input type="submit" value="{% trans "Update" %}"/>
            </div>
        </fieldset>
    </form>
    {% else %}
    <p>{% trans "Ви не адміністратор клубу" %}</p>
    {% endif %}
</div>

{% endblock %}

{% block extra_body %}

		<link type="text/css" href="{{ STATIC_URL }}pinax/css/jquery-ui-1.8.14.custom.css" rel="stylesheet" />	
   		<script type="text/javascript" src="{{ STATIC_URL }}pinax/js/topics.js"></script>
		<script type="text/javascript" src="{{ STATIC_URL }}pinax/js/jquery-1.5.1.min.js"></script>
		<script type="text/javascript" src="{{ STATIC_URL }}pinax/js/jquery-ui-1.8.14.custom.min.js"></script>

<script type="text/javascript">
	$(function() {

		$( "#id_date" ).datepicker({ dayNamesMin: ['Нед', 'Пон', 'Вівт', 'Сер', 'Чт', 'Пт', 'Суб'], firstDay: 1, dateFormat: 'yy-mm-dd',  monthNames: ['Січень','Лютий','Березень','Квітень','Травень','Червень','Липень','Серпень','Вересень','Жовтень','Листопад','Грудень'] });
	});
	</script>
{% endblock %}

templates/clubs/newmember.html
{% extends "clubs/base.html" %}


{% block body %}
<h2>Адміністратор розгляне вашу заявку.</h2>
{%endblock%}