apps/profiles/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls.defaults import *

urlpatterns = patterns('',
    url(r'^username_autocomplete/$', 'autocomplete_app.views.username_autocomplete_friends', name='profile_username_autocomplete'),
    url(r'^$', 'profiles.views.profiles', name='profile_list'),
    url(r'^profile/(?P<username>[\w\._-]+)/$', 'profiles.views.profile', name='profile_detail'),
    url(r'^edit/$', 'profiles.views.profile_edit', name='profile_edit'),
)

urls.py
# -*- coding: utf-8 -*-
from django.conf.urls.defaults import *
from django.conf import settings
from django.views.generic.simple import direct_to_template

from django.contrib import admin
admin.autodiscover()

#from account.openid_consumer import PinaxConsumer
from blog.feeds import BlogFeedAll, BlogFeedUser
from bookmarks.feeds import BookmarkFeed
from microblogging.feeds import TweetFeedAll, TweetFeedUser, TweetFeedUserWithFriends


tweets_feed_dict = {"feed_dict": {
    'all': TweetFeedAll,
    'only': TweetFeedUser,
    'with_friends': TweetFeedUserWithFriends,
}}

blogs_feed_dict = {"feed_dict": {
    'all': BlogFeedAll,
    'only': BlogFeedUser,
}}

bookmarks_feed_dict = {"feed_dict": { '': BookmarkFeed }}


if settings.ACCOUNT_OPEN_SIGNUP:
    signup_view = "account.views.signup"
else:
    signup_view = "signup_codes.views.signup"


urlpatterns = patterns('',
    url(r'^$', 'views.homepage_view', name="home"),

    url(r'^admin/invite_user/$', 'signup_codes.views.admin_invite_user', name="admin_invite_user"),
    url(r'^account/signup/$', signup_view, name="acct_signup"),
    
    (r'^photologue/', include('photologue.urls')),
    (r'^about/', include('about.urls')),
    (r'^account/', include('account.urls')),
    #(r'^openid/(.*)', PinaxConsumer()),
    (r'^bbauth/', include('bbauth.urls')),
    (r'^authsub/', include('authsub.urls')),
    (r'^profiles/', include('profiles.urls')),
    (r'^blog/', include('blog.urls')),
    (r'^tags/', include('tag_app.urls')),
    (r'^invitations/', include('friends_app.urls')),
    (r'^notices/', include('notification.urls')),
    (r'^messages/', include('messages.urls')),
    (r'^announcements/', include('announcements.urls')),
    (r'^tweets/', include('microblogging.urls')),
    (r'^tribes/', include('tribes.urls')),
    (r'^comments/', include('threadedcomments.urls')),
    (r'^robots.txt$', include('robots.urls')),
    (r'^i18n/', include('django.conf.urls.i18n')),
    (r'^bookmarks/', include('bookmarks.urls')),
    (r'^admin/(.*)', admin.site.root),
    (r'^photos/', include('photos.urls')),
    (r'^avatar/', include('avatar.urls')),
    (r'^swaps/', include('swaps.urls')),
    (r'^events/', include('events.urls')),
    (r'^locations/', include('locations.urls')),
    (r'^clubs/', include('clubs.urls')),
    (r'^universities/', include('universities.urls')),
    (r'^projects/', include('projects.urls')),
    
    (r'^feeds/tweets/(.*)/$', 'django.contrib.syndication.views.feed', tweets_feed_dict),
    (r'^feeds/posts/(.*)/$', 'django.contrib.syndication.views.feed', blogs_feed_dict),
    (r'^feeds/bookmarks/(.*)/?$', 'django.contrib.syndication.views.feed', bookmarks_feed_dict),
)

## @@@ for now, we'll use friends_app to glue this stuff together

from photos.models import Image

friends_photos_kwargs = {
    "template_name": "photos/friends_photos.html",
    "friends_objects_function": lambda users: Image.objects.filter(is_public=True, member__in=users),
}

from blog.models import Post

friends_blogs_kwargs = {
    "template_name": "blog/friends_posts.html",
    "friends_objects_function": lambda users: Post.objects.filter(author__in=users),
}

from microblogging.models import Tweet

friends_tweets_kwargs = {
    "template_name": "microblogging/friends_tweets.html",
    "friends_objects_function": lambda users: Tweet.objects.filter(sender_id__in=[user.id for user in users], sender_type__name='user'),
}


from bookmarks.models import Bookmark

friends_bookmarks_kwargs = {
    "template_name": "bookmarks/friends_bookmarks.html",
    "friends_objects_function": lambda users: Bookmark.objects.filter(saved_instances__user__in=users),
    "extra_context": {
        "user_bookmarks": lambda request: Bookmark.objects.filter(saved_instances__user=request.user),
    },
}

urlpatterns += patterns('',
    url('^photos/friends_photos/$', 'friends_app.views.friends_objects', kwargs=friends_photos_kwargs, name="friends_photos"),
    url('^blog/friends_blogs/$', 'friends_app.views.friends_objects', kwargs=friends_blogs_kwargs, name="friends_blogs"),
    url('^tweets/friends_tweets/$', 'friends_app.views.friends_objects', kwargs=friends_tweets_kwargs, name="friends_tweets"),
    url('^bookmarks/friends_bookmarks/$', 'friends_app.views.friends_objects', kwargs=friends_bookmarks_kwargs, name="friends_bookmarks"),
)

if settings.SERVE_MEDIA:
    urlpatterns += patterns('',
        (r'^site_media/', include('staticfiles.urls')),
    )

apps/clubs/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
from universities.models import University

from django.utils.translation import ugettext_lazy as _

    
class Club(models.Model):
    """
    Club with its details
    """
    title = models.CharField(_(u'Назва'), max_length=200)
    #university = models.ForeignKey(University)
    #while use just plain text university field
    university = models.CharField(max_length=1024, blank=True, null=False, default='')
    description = models.TextField(blank=True, null=False, default='')
    date = models.DateField(_(u'Дата створення'), default=datetime.now)
    address = models.TextField(_(u'Адреса'), blank=True)
    admin = models.ForeignKey(User)
    
    members = models.ManyToManyField(User, related_name='%(class)s_members', verbose_name=u"члени", blank=True)
    location = models.CharField(_(u'Місцезнаходження'), max_length=200)
	
    def __unicode__(self):
        return self.title
        
    def user_is_member(self, user):
        return user in self.members.all()        

class Verification(models.Model):
	club = models.ForeignKey(Club)
	member = models.ForeignKey(User)
	is_approved = models.BooleanField(u'Підтвердити', default = True)

apps/profiles/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.utils.translation import ugettext_lazy as _

from timezones.fields import TimeZoneField
from clubs.models import Club


class Profile(models.Model):
    
    ORG_WAYS = (
        (u'Методична робота', _(u'Методична робота')),
        (u'Розвиток англійських дебатів', _(u'Розвиток англійських дебатів')),
        (u'Організація дебатних заходів', _(u'Організація дебатних заходів')),
        (u'Співпраця із комерційними структурами', _(u'Співпраця із комерційними структурами')),
        (u'Співпраця  із іншими ГО', _(u'Співпраця  із іншими ГО')),
        (u'Співпраця із ЗМІ', _(u'Співпраця із ЗМІ')),
        (u'Не хочу займатись організаційними справами', _(u'Не хочу займатись організаційними справами')),
    )

    MEMBERS_FEE = (
        (u'5 грн', _(u'5 грн')),
        (u'10 грн', _(u'10 грн')),
        (u'15 грн', _(u'15 грн')),
        (u'20 грн', _(u'20 грн')),
        (u'30 грн', _(u'30 грн')),
        (u'50 грн', _(u'50 грн')),
        (u'Не можу сплачувати членський внесок', _(u'Не можу сплачувати членський внесок')),
    )
    
    user = models.ForeignKey(User, unique=True, verbose_name=_(u'user'))

    surname =  models.CharField(_(u'Прізвище'), max_length=200)
    name = models.CharField(_(u'Ім’я'), max_length=200)
    middle_name = models.CharField(_(u'По батькові'), max_length=200)
    birth_date = models.CharField(_(u'Дата народження'), max_length=300)
    address = models.TextField(_(u'Поштова адреса'), null=True, max_length=200)
    phone = models.CharField(_(u'Мобільний телефон'), null=True, max_length=200)
    skype = models.CharField(_(u'Логін Skype'), null=True, blank=True, max_length=200)
    icq = models.CharField(_(u'ICQ'), null=True, blank=True, max_length=200,)
    website = models.URLField(_(u'Адреса сторінки в соціальній мережі'), null=True, blank=True, verify_exists=False)
    education = models.CharField(_(u'Освіта (ВНЗ, факультет)'), blank=True, max_length=500)
    work = models.CharField(_(u'Місце роботи'), null=True, blank=True, max_length=600)
    experience = models.CharField(_(u'Досвід гри у дебати'), null=True, blank=True, max_length=600)
#    club = models.ForeignKey(Club, null=True, blank=True, unique=False, verbose_name=_(u'club'))
    social_work_exp = models.CharField(_(u'Досвід громадської роботи'), null=True, blank=True, max_length=600)
    desired_exp = models.TextField(_(u'Досвід, який хочу отримати'), null=True, blank=True)

    org_way = models.CharField(_(u'Організаційний напрямок'), null=True, choices = ORG_WAYS, max_length=200)
    members_fee = models.CharField(_(u'Членські внески'), choices = MEMBERS_FEE, max_length=200)  
    interests = models.TextField(_(u'Інтереси'), null=True, blank=True)
    vk_id = models.CharField(_(u'ID Вконтакті'), null=True, blank=True, max_length=30)
    about = models.TextField(_(u'about'), null=True, blank=True)

    
    def __unicode__(self):
        return self.name + ' ' + self.surname
    
    def __repr__(self):
        return self.name + ' ' + self.surname
    
    def get_absolute_url(self):
        return ('profile_detail', None, {'username': self.user.username})
    get_absolute_url = models.permalink(get_absolute_url)
    
    class Meta:
        verbose_name = _(u'profile')
        verbose_name_plural = _(u'profiles')

def create_profile(sender, instance=None, **kwargs):
    if instance is None:
        return
    profile, created = Profile.objects.get_or_create(user=instance)

post_save.connect(create_profile, sender=User)

class Verification(models.Model):
    md5_hash = models.CharField(_(u'Md5 for verivication'), null=True, blank=True, max_length=100)
    profile = models.OneToOneField(Profile, null=True, blank=True, verbose_name=_(u'profile'))

apps/profiles/forms.py
from django import forms
from profiles.models import Profile

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ('user', 'blogrss', 'timezone', 'language',
            'twitter_user', 'twitter_password')

apps/profiles/views.py
from django.core.urlresolvers import reverse
from django.shortcuts import render_to_response, get_object_or_404
from django.template import RequestContext
from django.http import HttpResponse, HttpResponseForbidden, HttpResponseRedirect
from django.conf import settings

from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

from django.utils.translation import ugettext_lazy as _
from django.utils.translation import ugettext

from friends.forms import InviteFriendForm
from friends.models import FriendshipInvitation, Friendship

from microblogging.models import Following

from profiles.models import Profile
from profiles.forms import ProfileForm

from avatar.templatetags.avatar_tags import avatar


if "notification" in settings.INSTALLED_APPS:
    from notification import models as notification
else:
    notification = None


def profiles(request, template_name="profiles/profiles.html", extra_context=None):
    if extra_context is None:
        extra_context = {}
    users = User.objects.all().order_by("-date_joined")
    search_terms = request.GET.get('search', '')
    order = request.GET.get('order')
    if not order:
        order = 'date'
    if search_terms:
        users = users.filter(username__icontains=search_terms)
    if order == 'date':
        users = users.order_by("-date_joined")
    elif order == 'name':
        users = users.order_by("username")
    return render_to_response(template_name, dict({
        'users': users,
        'order': order,
        'search_terms': search_terms,
    }, **extra_context), context_instance=RequestContext(request))


def profile(request, username, template_name="profiles/profile.html", extra_context=None):
    
    if extra_context is None:
        extra_context = {}
    
    other_user = get_object_or_404(User, username=username)
    
    if request.user.is_authenticated():
        is_friend = Friendship.objects.are_friends(request.user, other_user)
        is_following = Following.objects.is_following(request.user, other_user)
        other_friends = Friendship.objects.friends_for_user(other_user)
        if request.user == other_user:
            is_me = True
        else:
            is_me = False
    else:
        other_friends = []
        is_friend = False
        is_me = False
        is_following = False
    
    if is_friend:
        invite_form = None
        previous_invitations_to = None
        previous_invitations_from = None
        if request.method == "POST":
            if request.POST.get("action") == "remove": # @@@ perhaps the form should just post to friends and be redirected here
                Friendship.objects.remove(request.user, other_user)
                request.user.message_set.create(message=_("You have removed %(from_user)s from friends") % {'from_user': other_user})
                is_friend = False
                invite_form = InviteFriendForm(request.user, {
                    'to_user': username,
                    'message': ugettext("Let's be friends!"),
                })
    
    else:
        if request.user.is_authenticated() and request.method == "POST":
            if request.POST.get("action") == "invite": # @@@ perhaps the form should just post to friends and be redirected here
                invite_form = InviteFriendForm(request.user, request.POST)
                if invite_form.is_valid():
                    invite_form.save()
            else:
                invite_form = InviteFriendForm(request.user, {
                    'to_user': username,
                    'message': ugettext("Let's be friends!"),
                })
                invitation_id = request.POST.get("invitation", None)
                if request.POST.get("action") == "accept": # @@@ perhaps the form should just post to friends and be redirected here
                    try:
                        invitation = FriendshipInvitation.objects.get(id=invitation_id)
                        if invitation.to_user == request.user:
                            invitation.accept()
                            request.user.message_set.create(message=_("You have accepted the friendship request from %(from_user)s") % {'from_user': invitation.from_user})
                            is_friend = True
                            other_friends = Friendship.objects.friends_for_user(other_user)
                    except FriendshipInvitation.DoesNotExist:
                        pass
                elif request.POST.get("action") == "decline": # @@@ perhaps the form should just post to friends and be redirected here
                    try:
                        invitation = FriendshipInvitation.objects.get(id=invitation_id)
                        if invitation.to_user == request.user:
                            invitation.decline()
                            request.user.message_set.create(message=_("You have declined the friendship request from %(from_user)s") % {'from_user': invitation.from_user})
                            other_friends = Friendship.objects.friends_for_user(other_user)
                    except FriendshipInvitation.DoesNotExist:
                        pass
        else:
            invite_form = InviteFriendForm(request.user, {
                'to_user': username,
                'message': ugettext("Let's be friends!"),
            })
    
    previous_invitations_to = FriendshipInvitation.objects.invitations(to_user=other_user, from_user=request.user)
    previous_invitations_from = FriendshipInvitation.objects.invitations(to_user=request.user, from_user=other_user)
    
    return render_to_response(template_name, dict({
        "is_me": is_me,
        "is_friend": is_friend,
        "is_following": is_following,
        "other_user": other_user,
        "other_friends": other_friends,
        "invite_form": invite_form,
        "previous_invitations_to": previous_invitations_to,
        "previous_invitations_from": previous_invitations_from,
    }, **extra_context), context_instance=RequestContext(request))


@login_required
def profile_edit(request, form_class=ProfileForm, **kwargs):
    
    template_name = kwargs.get("template_name", "profiles/profile_edit.html")
    
    if request.is_ajax():
        template_name = kwargs.get(
            "template_name_facebox",
            "profiles/profile_edit_facebox.html"
        )
    
    profile = request.user.get_profile()
    
    if request.method == "POST":
        profile_form = form_class(request.POST, instance=profile)
        if profile_form.is_valid():
            profile = profile_form.save(commit=False)
            profile.user = request.user
            profile.save()
            return HttpResponseRedirect(reverse("profile_detail", args=[request.user.username]))
    else:
        profile_form = form_class(instance=profile)
    
    return render_to_response(template_name, {
        "profile": profile,
        "profile_form": profile_form,
    }, context_instance=RequestContext(request))

templates/profiles/base.html
{% extends "site_base.html" %}

{% load i18n %}

{% block body_class %}profile{% endblock %}

{% block subnav %}
    {% if user.is_authenticated %}
        <ul>
            <li><a href="{% url profile_detail user.username %} ">{% trans "Мій профіль" %}</a></li>
            <li><a href="{% url profile_list %} ">{% trans "Всі профілі" %}</a></li>
        </ul>
    {% else %}
        &nbsp;
    {% endif %}
{% endblock %}

templates/profiles/profile.html
{% extends "profiles/base.html" %}

{% load i18n %}
{% load avatar_tags %}
{% load uni_form %}
{% load group_tags %}
{% load microblogging_tags %}
{% load blog_tags %}
{% load tagging_tags %}
{% load photo_tags %}
{% load threadedcommentstags %}

{% block head_title %}Профіль {{ other_user.get_profile.name }}{% endblock %}

{% block body %}
 <script type="text/javascript" src="{{ STATIC_URL }}js/lightbox/prototype.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/lightbox/scriptaculous.js?load=effects,builder"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/lightbox/lightbox.js"></script>
<link rel="stylesheet" href="{{ STATIC_URL }}css/lightbox.css" type="text/css" media="screen" />
   
    <div class="right_panel">
        {% include "profiles/profile_right_panel.html" %}
    </div>
    
    <div class="left_panel">

                <h1>Профіль {{ other_user.get_profile.name }}</h1>
        <div class="vcard">
            <div id="profile_avatar">
                <div><img src="{% avatar_url other_user 80 %}" alt="Photo of {{ other_user }}" class="photo" /></div>
                {% if is_me %}
                <a href="{% url avatar_change %}" id="avatar_replace">(змінити)</a>
                {% endif %}
            </div>
            

            
            <div class="profile_info">
                
                {% if other_user.get_profile.surname %}<p><b>{% trans "Прізвище" %}</b>: {{ other_user.get_profile.surname }}</p>{% endif %}
                {% if other_user.get_profile.name %}<p><b>{% trans "Ім’я" %}</b>: <span class="fn">{{ other_user.get_profile.name }}</span></p>{% endif %}
                {% if other_user.get_profile.middle_name%}<p><b>{% trans "По батькові" %}</b>: {{ other_user.get_profile.middle_name }}</p>{% endif %}
                {% if other_user.get_profile.education%}<p><b>{% trans "Освіта" %}</b>: {{ other_user.get_profile.education }}</p>{% endif %}
                {% if other_user.club_set.all %}<p><b>{% trans "Дебатний клуб" %}</b>: {% for club in other_user.club_set.all %} <a class="url" href="{% url club_details club.id %}">{{ club }}</a> {% endfor %}</p>{% endif %}
                
                {% if request.user.is_authenticated %}
                    {% if other_user.get_profile.birth_date %}<p><b>{% trans "Дата народження" %}</b>: <span class="fn">{{ other_user.get_profile.birth_date }}</span></p>{% endif %}
                    {% if other_user.get_profile.skype%}<p><b>{% trans "Skype" %}</b>: {{ other_user.get_profile.skype }}</p>{% endif %}
                    {% if other_user.get_profile.vk_id %}
                    <p><b>{% trans "Сторінка vkontakte" %}</b>:
                        <a href="http://vk.com/id{{ other_user.get_profile.vk_id }}">http://vk.com/id{{ other_user.get_profile.vk_id }}</a>
                    </p>
                    {% endif %}
                    {% if other_user.get_profile.org_way %}<p><b>{% trans "Організаційний напрямок" %}</b>: {{ other_user.get_profile.org_way }}</p>{% endif %}
                    {% if other_user.get_profile.interests %}<p><b>{% trans "Інтереси" %}</b>: {{ other_user.get_profile.interests }}</p>{% endif %}
                {% endif %}
             
             {% comment %}
                {% if other_user.get_profile.website %}<p><b>{% trans "Website" %}</b>: <a class="url" target="_blank" href="{{ other_user.get_profile.website }}">{{ other_user.get_profile.website }}</a></p>{% endif %}
                

                {% if other_user.get_profile.org_way %}<p><b>{% trans "Організаційний напрямок" %}</b>: {{ other_user.get_profile.org_way }}</p>{% endif %}


                {% if other_user.get_profile.interests %}<p><b>{% trans "Інтереси" %}</b>: {{ other_user.get_profile.interests }}</p>{% endif %}
                
                
                {% if other_user.get_profile.address %}<p><b>{% trans "Поштова адреса" %}</b>: {{ other_user.get_profile.address }}</p>{% endif %}
                {% if other_user.email %}<p><b>{% trans "Електронна адреса" %}</b>: {{ other_user.email }}</p>{% endif %}
                {% if other_user.get_profile.phone%}<p><b>{% trans "Телефон" %}</b>: {{ other_user.get_profile.phone }}</p>{% endif %}


                {% if other_user.get_profile.icq%}<p><b>{% trans "ICQ" %}</b>: {{ other_user.get_profile.icq }}</p>{% endif %}

                {% if other_user.get_profile.work%}<p><b>{% trans "Місце роботи" %}</b>: {{ other_user.get_profile.work }}</p>{% endif %}
                {% if other_user.get_profile.experience%}<p><b>{% trans "Досвід гри у дебати" %}</b>: {{ other_user.get_profile.experience }}</p>{% endif %}



                {% if other_user.get_profile.social_work_exp%}<p><b>{% trans "Досвід громадської роботи" %}</b>: {{ other_user.get_profile.social_work_exp }}</p>{% endif %}
                {% if other_user.get_profile.desired_exp%}<p><b>{% trans "Досвід, який хочу отримати" %}</b>: {{ other_user.get_profile.desired_exp }}</p>{% endif %}


                {% if other_user.get_profile.members_fee %}<p><b>{% trans "Членські внески" %}</b>:  {{ other_user.get_profile.members_fee }}</p>{% endif %}

             {% endcomment %}



            </div>
            
            {% if is_me %}
                <p><a href="{% url profile_edit %}" rel="facebox">Редагувати профіль</a></p>
            {% endif %}
        {% comment %}    
            {% if user.is_authenticated %}

                {% if is_me %}
                {% else %}
                    {# @@@ this could be done with ajax, or at the very least turned into an inclusion tag #}
                    <div>
                        <form method="POST" action="{% url toggle_follow other_user %}">
                            {% if is_following %}
                                <input type="hidden" name="action" value="unfollow" /><input type="submit" value="{% trans "unfollow" %}"/>
                            {% else %}
                                <input type="hidden" name="action" value="follow" /><input type="submit" value="{% trans "follow tweets" %}"/>
                            {% endif %}
                        </form>
                    </div>
                    
                    {# @@@ this should be an inclusion tag #}
                    {% if is_friend %}
                        <p>{% blocktrans %}You are friends with {{ other_user }}.{% endblocktrans %} <a href="{% url messages_compose %}{{ other_user }}/">{% trans "Send a message" %}</a>.</p>
                        <div>
                            <form method="POST" action="">
                                <input type="hidden" name="action" value="remove" /><input type="submit" value="{% trans "remove from friends" %}"/>
                            </form>
                        </div>
                    {% else %}
                        {% if previous_invitations_from %}
                            <p>{% blocktrans %}{{ other_user }} has requested friendship.{% endblocktrans %}</p>
                            {% for invitation in previous_invitations_from %}
                                <div class="friendship_request">
                                    <p>From <a href="{% url profile_detail invitation.from_user.username %}">{{ invitation.from_user }}</a> ({{ invitation.sent }}):</p>
                                    <p class="invitation_message">{{ invitation.message }}</p>
                                    <form method="post" action="">
                                        <input type="hidden" name="invitation" value="{{ invitation.id }}"/>
                                        <input type="hidden" name="action" value="accept"/>
                                        <input type="submit" value="{% trans 'accept' %}" />
                                    </form>
                                    <form method="post" action="">
                                        <input type="hidden" name="invitation" value="{{ invitation.id }}"/>
                                        <input type="hidden" name="action" value="decline"/>
                                        <input type="submit" value="{% trans 'decline' %}" />
                                    </form>
                                </div>
                            {% endfor %}
                        {% else %}
                            {% if previous_invitations_to %}
                                <p>{% trans "Friendship request sent." %}</p>
                            {% else %}
                                <h2>{% trans "Add As Friend" %}</h2>
                                <form class="uniForm" method="POST" action="">
                                    <fieldset class="inlineLabels">
                                        {{ invite_form|as_uni_form }}
                                        <div class="form_block">
                                            <input type="hidden" name="action" value="invite" />
                                            <input type="submit" value="{% trans "invite" %}"/>
                                            {% blocktrans %}{{ other_user }} to be a friend.{%  endblocktrans %}
                                        </div>
                                    </fieldset>
                                </form>
                            {% endif %} {# previous_invitations_to #}
                        {% endif %} {# previous_invitations_from #}
                    {% endif %} {# is_friend #}
                    
                {% endif %} {# is me #}
                
                <h2>{% trans "Bookmarks" %}</h2>
                
                {% if other_user.saved_bookmarks.all %}
                    <table class="bookmarks narrow">
                        {% for bookmark_instance in other_user.saved_bookmarks.all.select_related %}
                            <tr class="{% cycle odd,even %} xfolkentry">
                                <td class="meta">
                                    {{ bookmark_instance.saved|date }}
                                    {# add who originally added it and when #}
                                </td>
                                <td>
                                    <h2><a class="taggedlink" href="{{ bookmark_instance.bookmark.url }}">{{ bookmark_instance.description }}</a></h2>
                                    <div class="url">{% if bookmark_instance.bookmark.get_favicon_url %}<img src="{{ bookmark_instance.bookmark.get_favicon_url }}" height="16" width="16"/> {% endif %}{{ bookmark_instance.bookmark.url }}</div>
                                    <div class="body description">{{ bookmark_instance.note|linebreaks }}</div>
                                </td>
                            </tr>
                        {% endfor %}
                    </table>
                {% else %}
                    {% url add_bookmark as add_bookmark_url %}
                    <p>{% blocktrans %}You haven't added any <a href="{{ add_bookmark_url }}">bookmarks</a> yet.{% endblocktrans %}</p>
                {% endif %}
                
                
                <h2>{% trans "Blog Posts" %}</h2>
                
                {% if other_user.added_posts.all %}
                    {% for blog_post in other_user.added_posts.all %}
                        {% show_blog_post blog_post %}
                    {% endfor %}
                {% else %}
                    {% trans "No blog posts yet." %}
                {% endif %}
                
                
                <h2>{% trans "Tweets" %}</h2>
                
                {% if user.is_authenticated and is_me %}
                    {% sent_tweet_listing user 0 is_me %}
                {% else %}
                    {% sent_tweet_listing other_user 0 is_me %}
                {% endif %}
                
                
                <h2>{% trans "Photos" %}</h2>
                
                {% public_photos for other_user as photos %}
                
                {% if photos %}
                    <div class="clearfix">
                    {% for photo in photos %}
                        <div class="gallery-photo-thumb">
                            <a href="{{ photo.get_display_url }}"rel="lightbox[hru]" ><img src="{{ photo.get_thumbnail_url }}" alt="{{ photo.title }}"/></a>
                        </div>
                    {% endfor %}
                    </div>
                {% else %}
                   {% trans "No photos uploaded yet." %}
                {% endif %}
                
            {% else %} {# not user.is_authenticated #}
                {% url acct_signup as signup_url %}
                {% url acct_login as login_url %}
                <p>{% blocktrans %}<a href="{{ signup_url }}">Sign up</a> and <a href="{{ login_url }}">log in </a> to add this person as a friend and see their tweets and blog posts.{% endblocktrans %}</p>
            {% endif %}
        {% endcomment %}    
        </div><!--/vcard-->
    </div>
{% endblock %}

{% block extra_body %}
    <script src="{{ STATIC_URL }}pinax/js/avatar.js" type="text/javascript"></script>
{% endblock %}

templates/profiles/profile_edit.html
{% extends "profiles/base.html" %}

{% load i18n %}

{% block head_title %}{% blocktrans %}Edit Profile{% endblocktrans %}{% endblock %}

{% block body %}
    
    <h1>{% trans "Редагування профіля" %}</h1>
    
    {% include "profiles/profile_form.html" %}
    
{% endblock %}

templates/profiles/profile_edit_facebox.html
{% load i18n %}

<h1>{% trans "Edit Profile" %}</h1>

{% include "profiles/profile_form.html" %}