apps/events/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('',


    # all ivent or latest ivent
    url(r'^$', 'events.views.events', name="events"),
    # your events
    url(r'^your_events/$', 'events.views.your_events', name='event_list_yours'),
    # Add event
    url(r'^add_event/$', 'events.views.add_event', name="add_event"),
    # an event details
    url(r'^details/(?P<id>\d+)/$', 'events.views.details', name="event_details"),
    url(r'^destroy/(?P<id>\d+)/$', 'events.views.destroy', name='event_destroy'),
    #edit event
    url(r'^edit/(?P<id>\d+)/$', 'events.views.edit', name='event_edit'),
    #join to event
    url(r'^join/(?P<id>\d+)/$', 'events.views.join', name='event_join'),
    #leave event
    url(r'^leave/(?P<id>\d+)/$', 'events.views.leave', name='event_leave'),
    # Map
    url(r'^map/$', 'events.views.map', name="map"),
    #answers
    url(r'^answers/(?P<id>\d+)/$', 'events.views.answers', name='event_answers'),
    #member list
    url(r'^members/(?P<id>\d+)/$', 'events.views.members', name='event_members'),
)

urls.py
# -*- coding: utf-8 -*-
from django.conf.urls.defaults import *
from django.conf import settings
from django.views.generic.simple import direct_to_template

from django.contrib import admin
admin.autodiscover()

#from account.openid_consumer import PinaxConsumer
from blog.feeds import BlogFeedAll, BlogFeedUser
from bookmarks.feeds import BookmarkFeed
from microblogging.feeds import TweetFeedAll, TweetFeedUser, TweetFeedUserWithFriends


tweets_feed_dict = {"feed_dict": {
    'all': TweetFeedAll,
    'only': TweetFeedUser,
    'with_friends': TweetFeedUserWithFriends,
}}

blogs_feed_dict = {"feed_dict": {
    'all': BlogFeedAll,
    'only': BlogFeedUser,
}}

bookmarks_feed_dict = {"feed_dict": { '': BookmarkFeed }}


if settings.ACCOUNT_OPEN_SIGNUP:
    signup_view = "account.views.signup"
else:
    signup_view = "signup_codes.views.signup"


urlpatterns = patterns('',
    url(r'^$', 'views.homepage_view', name="home"),

    url(r'^admin/invite_user/$', 'signup_codes.views.admin_invite_user', name="admin_invite_user"),
    url(r'^account/signup/$', signup_view, name="acct_signup"),
    
    (r'^photologue/', include('photologue.urls')),
    (r'^about/', include('about.urls')),
    (r'^account/', include('account.urls')),
    #(r'^openid/(.*)', PinaxConsumer()),
    (r'^bbauth/', include('bbauth.urls')),
    (r'^authsub/', include('authsub.urls')),
    (r'^profiles/', include('profiles.urls')),
    (r'^blog/', include('blog.urls')),
    (r'^tags/', include('tag_app.urls')),
    (r'^invitations/', include('friends_app.urls')),
    (r'^notices/', include('notification.urls')),
    (r'^messages/', include('messages.urls')),
    (r'^announcements/', include('announcements.urls')),
    (r'^tweets/', include('microblogging.urls')),
    (r'^tribes/', include('tribes.urls')),
    (r'^comments/', include('threadedcomments.urls')),
    (r'^robots.txt$', include('robots.urls')),
    (r'^i18n/', include('django.conf.urls.i18n')),
    (r'^bookmarks/', include('bookmarks.urls')),
    (r'^admin/(.*)', admin.site.root),
    (r'^photos/', include('photos.urls')),
    (r'^avatar/', include('avatar.urls')),
    (r'^swaps/', include('swaps.urls')),
    (r'^events/', include('events.urls')),
    (r'^locations/', include('locations.urls')),
    (r'^clubs/', include('clubs.urls')),
    (r'^universities/', include('universities.urls')),
    (r'^projects/', include('projects.urls')),
    
    (r'^feeds/tweets/(.*)/$', 'django.contrib.syndication.views.feed', tweets_feed_dict),
    (r'^feeds/posts/(.*)/$', 'django.contrib.syndication.views.feed', blogs_feed_dict),
    (r'^feeds/bookmarks/(.*)/?$', 'django.contrib.syndication.views.feed', bookmarks_feed_dict),
)

## @@@ for now, we'll use friends_app to glue this stuff together

from photos.models import Image

friends_photos_kwargs = {
    "template_name": "photos/friends_photos.html",
    "friends_objects_function": lambda users: Image.objects.filter(is_public=True, member__in=users),
}

from blog.models import Post

friends_blogs_kwargs = {
    "template_name": "blog/friends_posts.html",
    "friends_objects_function": lambda users: Post.objects.filter(author__in=users),
}

from microblogging.models import Tweet

friends_tweets_kwargs = {
    "template_name": "microblogging/friends_tweets.html",
    "friends_objects_function": lambda users: Tweet.objects.filter(sender_id__in=[user.id for user in users], sender_type__name='user'),
}


from bookmarks.models import Bookmark

friends_bookmarks_kwargs = {
    "template_name": "bookmarks/friends_bookmarks.html",
    "friends_objects_function": lambda users: Bookmark.objects.filter(saved_instances__user__in=users),
    "extra_context": {
        "user_bookmarks": lambda request: Bookmark.objects.filter(saved_instances__user=request.user),
    },
}

urlpatterns += patterns('',
    url('^photos/friends_photos/$', 'friends_app.views.friends_objects', kwargs=friends_photos_kwargs, name="friends_photos"),
    url('^blog/friends_blogs/$', 'friends_app.views.friends_objects', kwargs=friends_blogs_kwargs, name="friends_blogs"),
    url('^tweets/friends_tweets/$', 'friends_app.views.friends_objects', kwargs=friends_tweets_kwargs, name="friends_tweets"),
    url('^bookmarks/friends_bookmarks/$', 'friends_app.views.friends_objects', kwargs=friends_bookmarks_kwargs, name="friends_bookmarks"),
)

if settings.SERVE_MEDIA:
    urlpatterns += patterns('',
        (r'^site_media/', include('staticfiles.urls')),
    )

apps/clubs/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
from universities.models import University

from django.utils.translation import ugettext_lazy as _

    
class Club(models.Model):
    """
    Club with its details
    """
    title = models.CharField(_(u'Назва'), max_length=200)
    #university = models.ForeignKey(University)
    #while use just plain text university field
    university = models.CharField(max_length=1024, blank=True, null=False, default='')
    description = models.TextField(blank=True, null=False, default='')
    date = models.DateField(_(u'Дата створення'), default=datetime.now)
    address = models.TextField(_(u'Адреса'), blank=True)
    admin = models.ForeignKey(User)
    
    members = models.ManyToManyField(User, related_name='%(class)s_members', verbose_name=u"члени", blank=True)
    location = models.CharField(_(u'Місцезнаходження'), max_length=200)
	
    def __unicode__(self):
        return self.title
        
    def user_is_member(self, user):
        return user in self.members.all()        

class Verification(models.Model):
	club = models.ForeignKey(Club)
	member = models.ForeignKey(User)
	is_approved = models.BooleanField(u'Підтвердити', default = True)

apps/events/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
#from django.contrib.contenttypes.models import ContentType
#from django.contrib.contenttypes import generic
from photos.models import PhotoSet
#from photologue.models import *
from stdimage import StdImageField
#from tagging.fields import TagField

from django.utils.translation import ugettext_lazy as _
from django.utils import simplejson

TITLE_EXCERPT_LENGTH = 22

class Event(models.Model):
    """
    An event with its details
    """
    title = models.CharField(_(u'Назва'), max_length=50)
    description = models.TextField(_(u'Опис'), blank=True)
    date_begin = models.DateTimeField(_(u'Початок'), default=datetime.now)
    date_end = models.DateTimeField(_(u'Кінець'), default=datetime.now)
    address = models.TextField(_(u'Адреса проведення'), blank=True)
    date_added = models.DateTimeField(_(u'Дата створення'), default=datetime.now, editable=False)
    creator = models.ForeignKey(User, related_name="%(class)s_created")
    members = models.ManyToManyField(User, related_name='events', verbose_name=_(u'Учасники'))
    location = models.CharField(_(u'location'), max_length=200)
    questions = models.TextField(blank=True)
    approved = models.BooleanField(_(u'Підтверджено'), default = False)
    eventimage = StdImageField(_(u'Лого події'),upload_to = "photos/", size=(400, 300), thumbnail_size=(100, 100))
    gallery = models.ForeignKey(PhotoSet, blank = True, null = True)
    def __unicode__(self):
        return self.title
        
    def user_is_member(self, user):
        return user in self.members.all()
        
    @property
    def title_excerpt(self):
        if len(self.title) > TITLE_EXCERPT_LENGTH:
            result = ''.join([self.title[:TITLE_EXCERPT_LENGTH], '...'])
        else:
            result = self.title
        return result
        
    def get_table_data(self):
        """
        Get answer table data
        """
        data = {}
                
        if self.questions != "":
        
            questions = simplejson.loads(self.questions)
            
            data['columns'] = [_(u"Учасник")]
            
            for question in questions:
                data['columns'].append(question['title'])
                
            answer_lists = AnswerList.objects.filter(event=self)
            
            data['rows'] = []
            
            for answer_list in answer_lists:
                answers = simplejson.loads(answer_list.value)
                row = []
                row.append({"data": unicode(answer_list.user.get_profile()),
                            "profile": answer_list.user.username, "type":"profile"})
                for i, answer in enumerate(answers):
                    if questions[i]['type'] == "one":
                        row.append({"data": questions[i]['options'][int(answer)-1]})
                    elif questions[i]['type'] == "multi":
                        items = []
                        for j in answer:
                            items.append(questions[i]['options'][int(j)-1])
                        row.append({"data": items, "type":"list"})
                    else:
                        row.append({"data": answer})
                data['rows'].append(row)
        
        return data
        
    def get_excel_data(self):
        """
        Get data for ExcelResponse
        """
        data = []
                
        if self.questions != "":
        
            questions = simplejson.loads(self.questions)
            
            headers = [unicode(_(u"Учасник"))]
            
            for question in questions:
                headers.append(question['title'])
                
            data.append(headers)
            
            answer_lists = AnswerList.objects.filter(event=self)
            
            for answer_list in answer_lists:
                answers = simplejson.loads(answer_list.value)
                row = []
                row.append(unicode(answer_list.user.get_profile()))
                for i, answer in enumerate(answers):
                    if questions[i]['type'] == "one":
                        row.append(questions[i]['options'][int(answer)-1])
                    elif questions[i]['type'] == "multi":
                        value = u""
                        for j in answer:
                            value = value + u"- %s\n" % questions[i]['options'][int(j)-1]
                        row.append(value)
                    else:
                        row.append(answer)
                data.append(row)
        
        return data
class AnswerList(models.Model):
    event = models.ForeignKey(Event)
    user = models.ForeignKey(User)
    value = models.TextField()

apps/events/forms.py
# -*- coding: utf-8 -*-
from django import forms
from events.models import Event, AnswerList
from django.utils.translation import ugettext_lazy as _

from django.utils import simplejson
from django.forms.widgets import Textarea
from django.utils.safestring import mark_safe
from django.forms.util import flatatt
from django.utils.html import conditional_escape
from django.utils.encoding import force_unicode

class EventAddressWidget(Textarea):
    def render(self, name, value, attrs=None):
        result = super(EventAddressWidget, self).render(name, value, attrs=attrs)
        result += mark_safe(u'<input style ="float: right; margin-right: 33px; margin-top: 5px;"  type="button" value="Знайти на мапі" onclick="codeAddress()">')
        return result


class EventForm(forms.ModelForm):
    questions = forms.CharField(widget=forms.HiddenInput, required = False)
    location = forms.CharField(initial="(48.464954, 35.044956)", #dnipropetrovsk
                               widget=forms.HiddenInput)
    address = forms.CharField(label = _(u'Адреса проведення'),widget=EventAddressWidget())

    class Meta:
        model = Event
        exclude = ('members', 'creator', 'approved', 'gallery')
        
        
    def __init__(self, user=None, *args, **kwargs):
        self.user = user        
        super(EventForm, self).__init__(*args, **kwargs)
        
class QuestionsForm(forms.Form):
    """
    Dynamic form that allows the user to change
    and then verify the data that was parsed
    """
    def __init__(self, event, user, *args, **kwargs):
        self.event = event
        self.user = user
        super(QuestionsForm, self).__init__(*args, **kwargs)
        
    def setFields(self, kwds):
        """
        Set the fields in the form
        """
        keys = kwds.keys()
        keys.sort()
        for k in keys:
            self.fields[k] = kwds[k]
            
    def setQuestions(self, jquestions):
        """
        Set the questions in the form
        """
        fields = {}
            
        questions = simplejson.loads(jquestions)
        
        for i, question in enumerate(questions):
            if question['type'] == 'free':
                fields['q'+str(i+1)] = forms.CharField(label=question['title'],
                                                       widget=forms.Textarea)
            else :
                choices_list = []
                for j, option in enumerate(question['options']):
                     choices_list.append((j+1, option))
                if question['type'] == 'one':
                    fields['q'+str(i+1)] = forms.ChoiceField(label=question['title'],
                                                           help_text=_(u"Оберіть одну відповідь"),
                                                           widget=forms.RadioSelect,
                                                           choices=choices_list,
                                                           )
                elif question['type'] == 'multi':
                    fields['q'+str(i+1)] = forms.MultipleChoiceField(label=question['title'],
                                                         help_text = _(u"Оберіть кілька відповідей"),
                                                         widget=forms.CheckboxSelectMultiple,
                                                         choices=choices_list,
                                                         )
            
        self.setFields(fields)
            
    def setData(self, kwds):
        """
        Set the data to include in the form
        """
        for name,field in self.fields.items():
            self.data[name] = field.widget.value_from_datadict(kwds,
                                                               self.files,
                                                               self.add_prefix(name))
        self.is_bound = True
            
    def validate(self, post):
        """
        Validate the contents of the form
        """
        self.cleaned_data = {}
        for name,field in self.fields.items():
            value = field.widget.value_from_datadict(post,
                                                     self.files,
                                                     self.add_prefix(name))
            try:
                self.cleaned_data[name] = field.clean(value)
            except forms.ValidationError, e:
                self.errors[name] = e.messages
                
    def save(self):
        data = [self.cleaned_data[key] for key in sorted(self.cleaned_data.iterkeys())]
        answer_list = AnswerList(event=self.event, user=self.user)
        answer_list.value = simplejson.dumps(data, ensure_ascii = False)
        answer_list.save()

templates/events/add_event.html
{% extends "events/base.html" %}

{% load i18n %}
{% load uni_form %}


{% block body_param %} onload="initialize()" {% endblock %}


{% block body %}
    <div class="right_panel">
        {% include "map.html" %}

    </div>
    
    <div class="left_panel">
    <h1>Нова подія</h1>

    <form class="uniForm" id="edit-profile" method="POST" enctype="multipart/form-data" action="">
        <fieldset class="inlineLabels">
            {{ event_form|as_uni_form }}      
   
                       <div class="form_block">
                <input type="hidden" name="action" value="add" />
                <input type="hidden" name="photoset" value="0" />
            </div>
        </fieldset>
    </form>
    <h2>{% trans "Додати питання" %}</h2>
    <form class="uniForm">
        <fieldset class="inlineLabels">
            <ul id="itemcontainer">
            </ul>
            <div class="form_block" style="padding: 7px;">
                <a id="additem" href="javascript: void(0)">{% trans "Додати питання" %}</a>
            </div>
            <div class="form_block">
                <input id="pseudosubmit" type="button" value="{% trans "Зберегти" %}">
                <input id="pseudosubmitphotoset" type="button" value="{% trans "Зберегти і перейти до альбому" %}">
            </div>
        </fieldset>
    </form>
</div>

{% endblock %}

{% block extra_body %}

        <link type="text/css" href="{{ STATIC_URL }}pinax/css/jquery-ui-1.8.14.custom.css" rel="stylesheet" />    
        <script type="text/javascript" src="{{ STATIC_URL }}pinax/js/topics.js"></script>

        <script type="text/javascript" src="{{ STATIC_URL }}pinax/js/jquery-ui-1.8.14.custom.min.js"></script>
        <script type="text/javascript" src="{{ STATIC_URL }}pinax/js/jquery-ui-timepicker-addon.js"></script>
        <script type="text/javascript" src="{{ STATIC_URL }}pinax/js/jquery.json-2.2.min.js"></script>
        <link type="text/css" href="{{ STATIC_URL }}pinax/css/customquestions.css" rel="stylesheet" />
        <script type="text/javascript" src="{{ STATIC_URL }}pinax/js/customquestions.js"></script>
        


<script type="text/javascript">

$(function() {
		
	$.datepicker.regional['ru'] = {
		closeText: 'Закрити',
		prevText: '<Попер',
		nextText: 'Наст>',
		currentText: 'Сьогодні',
		monthNames: ['Січень','Лютий','Березень','Квітень','Травень','Червень','Липень','Серпень','Вересень','Жовтень','Листопад','Грудень'],
		monthNamesShort: ['Січ','Лют','Бер','Квіт','Трав','Черв','Лип','Серп','Вер','Жов','Лист','Груд'],
		dayNames: ['неділя','понеділок','вівторок','середа','четвер','п\'ятниця','субота'],
		dayNamesShort: ['нед','пон','вівт','сер','чт','пт','суб'],
		dayNamesMin: ['Нд', 'Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб'], 
		weekHeader: 'Не',
		dateFormat: 'yy-mm-dd',
		firstDay: 1,
		isRTL: false,
		showMonthAfterYear: false,
		yearSuffix: ''
	};
	$.datepicker.setDefaults($.datepicker.regional['ru']);

	$.timepicker.regional['ru'] = {
		timeOnlyTitle: 'Виберіть час',
		timeText: 'Час',
		hourText: 'Години',
		minuteText: 'Хвилини',
		secondText: 'Секунди',
		millisecText: 'Мілісекунди',
		currentText: 'Зараз',
		closeText: 'Закрити',
		ampm: false,
		hourGrid: 4,
		minuteGrid: 10,
		timeFormat: 'hh:mm'
	};
	
	$.timepicker.setDefaults($.timepicker.regional['ru']);
    
    $( "#id_date_begin" ).datetimepicker();
	$( "#id_date_end" ).datetimepicker();
	
    $('#edit-profile').testeditor();
    $('#pseudosubmit').click(function() {
        $('#edit-profile').submit();
    });
    $('#pseudosubmitphotoset').click(function() {
        $('#edit-profile input:hidden[name="photoset"]').val("1");
        $('#edit-profile').submit();
    });
});
    </script>
{% endblock %}

templates/events/answers.html
{% extends "events/base.html" %}

{% load i18n %}

{% block body %}
    <h1>{{ event.title }}</h1>
    {% if table.rows %}
        <h2>{% trans "Відповіді" %}</h2>
        <div style="overflow: auto;">
        <table cellpadding="5" cellspacing="0" border="0" class="answer-list">
            <tr>
                {% for column in table.columns %}
                <th>{{ column }}</th>
                {% endfor %}
            </tr>
            {% for row in table.rows %}
                <tr class="{% cycle odd,even %}">
                {% for value in row %}
                    {% ifequal value.type "list" %}
                        <td nowrap>
                            <ul>{{ value.data|unordered_list }}</ul>
                        </td>
                    {% else %}{% ifequal value.type "profile" %}
                        <td nowrap>
                            <a href="{% url profile_detail value.profile %}">{{ value.data }}</a>
                        </td>
                    {% else %}
                        <td>{{ value.data }}</td>
                    {% endifequal %}{% endifequal %}
                {% endfor %}
                </tr>
            {% endfor %}
        </table>
        </div>
        <a href="?action=export"> <P> {% trans "Завантажити у форматі XLS" %} </P> </a>
    {% else %}
        <p>{% trans "Відповідей поки що немає." %}</p>
    {% endif %}
{% endblock %}

templates/events/details.html
{% extends "events/base.html" %}

{% load i18n %}
{% load humanize %}
{% load pagination_tags %}
{% load tagging_tags %}
{% load group_tags %}
{% load threadedcommentstags %}
{% load theme_tags %}
{% load comments_tag %}
{% load avatar_tags %}

{% block head_title %}{% blocktrans %}Деталі події{% endblocktrans %}{% endblock %}




{% block body_param %} onload="initialize()" {% endblock %}
{% block body %}

<script type="text/javascript" src="{{ STATIC_URL }}js/lightbox/prototype.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/lightbox/scriptaculous.js?load=effects,builder"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/lightbox/lightbox.js"></script>
<link rel="stylesheet" href="{{ STATIC_URL }}css/lightbox.css" type="text/css" media="screen" />
<div class="right_panel">
       <h1>{% trans "Місце проведення" %}</h1>
  {% include "map.html" %}
  <p><div id="div_id_address" class="ctrlHolder">
	           <label for="id_address">                    
	                  <b>Адреса:</b><br>
 
	           </label>
	      {{ event.address }} 
      </div></p>


    </div>
    
      <div class="left_panel">


    <h1>{% trans "Деталі події" %}</h1>

	<div id="div_id_title" class="ctrlHolder">
        <h3>  {{ event.title }} </h3>

    </div><P>
	<div id="div_id_details" class="ctrlHolder">
	           <label for="id_details">                    
                   <b>Деталі:</b><br>
	           </label>
      {{ event.description|safe }}
  </div></P>


	<P>
<div id="div_id_date" class="ctrlHolder">
	           <label for="id_date"> <b>Початок:</b> </label>   {{ event.date_begin|date:"D d M Y h:m" }}  <br>
	           <label for="id_end"> <b>Кінець:</b> </label>     {{ event.date_end|date:"D d M Y h:m" }} 
	           

    </div></P>


	<div id="div_id_date" class="ctrlHolder">
	           <label for="id_date">                    
                   <b>Ініціатор:</b>
	           </label>
	        {{ event.creator.get_profile.surname }} {{ event.creator.get_profile.name }} 
             </div>



	{% if not is_member %}
		<a href="/events/join/{{ event.id }}"> <P> Приєднатись до події </P> </a>
	{% endif %}

        <h3>Учасники події:</h3>

	<div name = "members" class="thumb-row clearfix">
    {% for member in event.members.all %}
        <div name = "member" style="float:left; margin: 10px; text-align: center">  
			<div name = "avatar">
				<a href="{% url profile_detail member.username %}">
					<img src="{% avatar_url member 80 %}" alt="Avatar of {{ member.get_profile }}"/> </a> </div>
			<div name = "username">
				<a href="{% url profile_detail member.username %}"> {{ member.get_profile }} </a> </div>
		</div>
	{% endfor %}
	

</div>

	{% if is_member %}
		<!-- <a href="/events/leave/{{ event.id }}"> <P>Покинути подію</P> </a> -->
		<a href="/events/members/{{ event.id }}"> <P> Всі учасники </P> </a>
	{% endif %}

{% if photoset.image_set.count%}      <h3>Альбом події</h3>{%endif%}
<div class="thumb-row clearfix">
{% for image in photoset.image_set.all %}
<div class="gallery-photo-thumb">
    <div class="thumb-image">
        <a href="{{image.get_display_url}}" rel="lightbox[hri]" title = {{image.title}}>
  <img src="{{image.get_thumbnail_url}}" />
  </div>
{{image.title}}
        </a>
 
    </div>    
{% endfor %}
</div>

	<div name = "comments" style="clear:left">

        <h3>Коментарі події:</h3>
         	{% comments event %}

	</div>
</div>
{% endblock %}

templates/events/edit.html
{% extends "events/base.html" %}

{% load i18n %}
{% load uni_form %}



{% block body_param %} onload="initialize()" {% endblock %}
{% block body %}
   <div class="right_panel">
        {% include "map.html" %}
    </div>
    
<div class="left_panel">
    <h1>Редагування події</h1>
    <form class="uniForm" id="edit-profile" method="POST" enctype="multipart/form-data" action="" >
        <fieldset class="inlineLabels">
            {{ event_form|as_uni_form }}
            
            <div class="form_block">
                <input type="hidden" name="action" value="update" />
                <input type="submit" value="{% trans "Зберегти" %}" /> 
                <a  href="/photos/edit/photoset/{{event.gallery.id}}" ><input type="button" value="Редагувати альбом події"></a>

            </div>
        </fieldset>
    </form>
  </div>

{% endblock %}

{% block extra_body %}



        <script src="{{ STATIC_URL }}pinax/js/jquery-1.3.2.min.js" type="text/javascript"></script>
        <script src="{{ STATIC_URL }}pinax/js/base.js" type="text/javascript"></script>
        <script src="{{ STATIC_URL }}uni_form/uni-form.jquery.js" type="text/javascript"></script>
        {% include "facebox_js.html" %}
		<link type="text/css" href="{{ STATIC_URL }}pinax/css/jquery-ui-1.8.14.custom.css" rel="stylesheet" />	
   		<script type="text/javascript" src="{{ STATIC_URL }}pinax/js/topics.js"></script>
		<script type="text/javascript" src="{{ STATIC_URL }}pinax/js/jquery-1.5.1.min.js"></script>
		<script type="text/javascript" src="{{ STATIC_URL }}pinax/js/jquery-ui-1.8.14.custom.min.js"></script>
	    <script type="text/javascript" src="{{ STATIC_URL }}pinax/js/jquery-ui-timepicker-addon.js"></script>
		<script type="text/javascript" src="{{ STATIC_URL }}pinax/js/jquery.json-2.2.min.js"></script>
		<link type="text/css" href="{{ STATIC_URL }}pinax/css/customquestions.css" rel="stylesheet" />
		<script type="text/javascript" src="{{ STATIC_URL }}pinax/js/customquestions.js"></script>


<script type="text/javascript">

$(function() {
	$.datepicker.regional['ru'] = {
		closeText: 'Закрити',
		prevText: '<Попер',
		nextText: 'Наст>',
		currentText: 'Сьогодні',
		monthNames: ['Січень','Лютий','Березень','Квітень','Травень','Червень','Липень','Серпень','Вересень','Жовтень','Листопад','Грудень'],
		monthNamesShort: ['Січ','Лют','Бер','Квіт','Трав','Черв','Лип','Серп','Вер','Жов','Лист','Груд'],
		dayNames: ['неділя','понеділок','вівторок','середа','четвер','п\'ятниця','субота'],
		dayNamesShort: ['нед','пон','вівт','сер','чт','пт','суб'],
		dayNamesMin: ['Нд', 'Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб'], 
		weekHeader: 'Не',
		dateFormat: 'yy-mm-dd',
		firstDay: 1,
		isRTL: false,
		showMonthAfterYear: false,
		yearSuffix: ''
	};
	$.datepicker.setDefaults($.datepicker.regional['ru']);

	$.timepicker.regional['ru'] = {
		timeOnlyTitle: 'Виберіть час',
		timeText: 'Час',
		hourText: 'Години',
		minuteText: 'Хвилини',
		secondText: 'Секунди',
		millisecText: 'Мылысекунди',
		currentText: 'Зараз',
		closeText: 'Закрити',
		ampm: false,
		hourGrid: 4,
		minuteGrid: 10,
		timeFormat: 'hh:mm'
	};
	
	$.timepicker.setDefaults($.timepicker.regional['ru']);
    
    $( "#id_date_begin" ).datetimepicker();
	$( "#id_date_end" ).datetimepicker();
  
  $( "#edit-profile" ).testeditor();
	});
	</script>
{% endblock %}